# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sairo < Formula
  desc "Fast S3 storage browser CLI — sub-second queries on petabyte-scale buckets"
  homepage "https://github.com/ashwathstephen/sairo"
  version "3.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ashwathstephen/sairo/releases/download/v3.6.1/sairo_3.6.1_darwin_amd64.tar.gz"
      sha256 "554476727467f43c5cb595aebaa76380823b876731ed6d47ee35ae1e320086ee"

      define_method(:install) do
        bin.install "sairo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ashwathstephen/sairo/releases/download/v3.6.1/sairo_3.6.1_darwin_arm64.tar.gz"
      sha256 "67ee25629c23552d54c5d140f386f18ca6f99ea936e9b1c42b50418d3010c971"

      define_method(:install) do
        bin.install "sairo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ashwathstephen/sairo/releases/download/v3.6.1/sairo_3.6.1_linux_amd64.tar.gz"
      sha256 "7335f25eebfbc33cfe8d201e8f7fa61d87d2915b88dcd9904567f47fd6ad84ff"
      define_method(:install) do
        bin.install "sairo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ashwathstephen/sairo/releases/download/v3.6.1/sairo_3.6.1_linux_arm64.tar.gz"
      sha256 "fbf4e7d1a77fb17ac75cd998dc012e20cfdb202ca67ed500ec548b9abb7f87f8"
      define_method(:install) do
        bin.install "sairo"
      end
    end
  end

  test do
    system "#{bin}/sairo", "version"
  end
end
