# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sairo < Formula
  desc "Fast S3 storage browser CLI — sub-second queries on petabyte-scale buckets"
  homepage "https://github.com/ashwathstephen/sairo"
  version "3.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ashwathstephen/sairo/releases/download/v3.2.0/sairo_3.2.0_darwin_amd64.tar.gz"
      sha256 "f3c7604b4b0c2df11dae7dd424953a997f44d4acca133025f03d601dd4f78264"

      define_method(:install) do
        bin.install "sairo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ashwathstephen/sairo/releases/download/v3.2.0/sairo_3.2.0_darwin_arm64.tar.gz"
      sha256 "11a9c6c1ece33a5835a63ce271dfd2999cad554c17ccb9e906211e8a636ce86b"

      define_method(:install) do
        bin.install "sairo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ashwathstephen/sairo/releases/download/v3.2.0/sairo_3.2.0_linux_amd64.tar.gz"
      sha256 "3e427ab0f5dc97bde4998d43e612eef2b46ed58b17164671ed7655edbf01fbb9"
      define_method(:install) do
        bin.install "sairo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ashwathstephen/sairo/releases/download/v3.2.0/sairo_3.2.0_linux_arm64.tar.gz"
      sha256 "1a864c50b8da813614a0bfc748dac9bab0b538520be8b8aa39e6ebe35a6da06d"
      define_method(:install) do
        bin.install "sairo"
      end
    end
  end

  test do
    system "#{bin}/sairo", "version"
  end
end
